### ISSUE TITLE
LazyRepetition error with artifact_collector on Live

### ISSUE THREAD

**Issue by DeKe42** [google/rekall#285]
Hi,

I am currently trying to use rekall as a library to gather some triage data. I wrote the following artifact:

```
name: netscan
doc: Network connections
sources:
    - type: REKALL_EFILTER
      attributes:
          query: >-
            SELECT pid, protocol, remote_addr, state, created, local_addr, owner from netscan(scan_physical: True)
          type_name: RekallNETSCAN
          image_type:
            - Windows

          fields:
            - name: pid
              type: int 
            - name: protocol
              type: unicode
            - name: local_addr
              type: unicode
            - name: remote_addr
              type: unicode 
            - name: state
              type: unicode
            - name: owner
              type: unicode
            - name: created
              type: unicode
```

If I use this artifact on a live system (if it matters, it's a Windows 10 machine, which is why there is scan_physical) like so:

```
artifact_collector(artifact_files=["D:\\EFILTER-Artifacts.yaml"], artifacts=["netscan"], writer="Zip", output_path="D:\\results.zip")
```

It will work for a while and then error out with the following exception:
`ValueError: LazyRepetition LazyRepetition(generator_func=<bound method WinNetscan.collect_as_dicts of Plugin: netscan (WinNetscan)>, value_type=<type 'dict'>) was previously able to iterate its generator up to idx 258, but this time iteration stopped after idx 253! Generator function <bound method WinNetscan.collect_as_dicts of Plugin: netscan (WinNetscan)> is not stable.`
Stacktrace is attached: [Exception.txt](https://github.com/google/rekall/files/1285219/Exception.txt)

I guess this is caused by changing network connections on a live system. Or am I doing something wrong?

Thanks!
